[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
library = { path = "lib/library" }

[build-system]
requires=["poetry-core>=1.0.0a9"]
build-backend="poetry.core.masonry.api"
